# Используем официальный образ Python
FROM python:3.11-slim

# Устанавливаем зависимости
WORKDIR /app
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код в контейнер
COPY postgres_handler.py /app

# Экспонируем порт 5000
EXPOSE 5000

# Команда для запуска Flask-приложения
CMD ["python", "postgres_handler.py"]
